name: Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.5
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: antfu

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
